# Generated by Django 5.2.10 on 2026-02-01 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0002_gastos_usuario_creador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gastos',
            name='usuario_creador',
        ),
    ]
