# Generated by Django 5.2.10 on 2026-02-01 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0003_remove_gastos_usuario_creador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastos',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
