# Generated by Django 5.2.10 on 2026-02-01 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0004_alter_gastos_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastos',
            name='soporte',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
