# Generated by Django 5.2.10 on 2026-02-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0005_alter_gastos_soporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastos',
            name='soporte',
            field=models.ImageField(blank=True, null=True, upload_to='soportes/'),
        ),
    ]
